INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('1', 'Inicio', 'Inicio');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('2', 'Peliculas', 'Peliculas');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('3', 'Clientes', 'Clientes');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('4', 'Actores', 'Actores');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('5', 'Generos', 'Generos');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('6', 'Empleados', 'Empleados');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('7', 'Prestamos', 'Prestamos');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('8', 'Parametrizacion', 'Parametrizacion');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('9', 'Tiendas', 'Tiendas');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('10', 'Autorizacion', 'Autorizacion');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('11', 'Reportes', 'Reportes');
INSERT INTO `videotienda`.`film` (`film_id`, `description`, `last_update`, `length`, `rating`, `release_year`, `rental_duration`, `rental_rate`, `replacement_cost`, `special_features`, `title`, `category`, `language_id`, `original_language_id`) VALUES ('3', 'Latin Awards', '2016-11-09 21:59:46', '1', 'S', '2016-11-16', '11', '6443', '34554', 'Jhan Glock', 'La Suicida', '1', '2', '1');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('1', 'Inicio', 'Inicio');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('2', 'Peliculas', 'Peliculas');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('3', 'Clientes', 'Clientes');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('4', 'Actores', 'Actores');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('5', 'Generos', 'Generos');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('6', 'Empleados', 'Empleados');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('7', 'Prestamos', 'Prestamos');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('8', 'Parametrizacion', 'Parametrizacion');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('9', 'Tiendas', 'Tiendas');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('10', 'Autorizacion', 'Autorizacion');
INSERT INTO `t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('11', 'Reportes', 'Reportes');
INSERT INTO `country` (`country_id`, `country`, `last_update`) VALUES ('1', 'Colombia', '2016-10-06');
INSERT INTO `city` (`city_id`, `city`, `country_id`) VALUES ('1', 'Armenia', '1');
INSERT INTO `city` (`city_id`, `city`, `country_id`) VALUES ('2', 'Bogota', '1');
INSERT INTO `videotienda`.`address` (`address`, `address2`, `district`, `last_update`, `phone`, `postal_code`, `city_id`) VALUES ('B/ laureles', 'null', 'comuna 3', '2007-10-15', '320735', '2672762', '1');
INSERT INTO `videotienda`.`address` (`address`, `address2`, `district`, `last_update`, `phone`, `postal_code`, `city_id`) VALUES ('B/ las americas', 'null', 'comuna 7', '2010-11-15', '72939', '53562', '1');
INSERT INTO `videotienda`.`store` (`store_id`, `last_update`, `Nombre_tienda`, `address_id`) VALUES ('17', '2010-10-26', 'Video net', '1');
INSERT INTO `videotienda`.`store` (`store_id`, `last_update`, `Nombre_tienda`, `address_id`) VALUES ('23', '2014-10-26', 'Video Armenia', '2');