INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('1', 'Inicio', 'Inicio');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('2', 'Vender Peliula', 'Vender Pelicula');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('3', 'Gestionar Pelicula', 'Gestionar Pelicula');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('4', 'Trasladar Ciudad', 'Trasladar Ciudad');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('5', 'Gestionar Actores', 'Gestionar Actores');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('6', 'Gestionar Empleado', 'Gestionar Empleado');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('7', 'Ciudad', 'Ciudad');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('8', 'Gestionar Tiendas', 'Gestionar Tiendas');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('9', 'Roles', ' Roles');
INSERT INTO `videotienda`.`t_acceso` (`ID_ACCESO`, `NOMBRE`, `PANTALLA`) VALUES ('10', 'Reportes Venta Alquiler', 'Reportes Venta Alquiler');
